version: '3'

services:
  git:
    image: jkarlos/git-server-docker
    ports:
      - "2222:22"
    expose:
      - 2222
    volumes:
      - ~/git-server/keys:/git-server/keys
      - ~/git-server/repos:/git-server/repos